<?php
/**
 * Created by PhpStorm.
 * User: HaiMinh
 * Date: 6/2/2019
 * Time: 9:18 AM
 */
/*
 * Static là biến tĩnh,như biến toàn cục,
 * nó lấy giá trị cuối cùng mà nó được thực hiện
 */
class ConNguoi
{
    private static $name = 'amonymouse';

    public function setName($name)
    {
        //Gọi phương thức hoặc thuộc tính tĩnh trong class
        self::$name = $name;
    }

    public function getName()
    {
        return self::$name;
    }
    public static function showAll(){
        return self::getName();
    }
}

//khởi tạo đối tượng con người
$ten = new ConNguoi();
//set name cho đối tượng
$ten->setName('Lương Hải Minh');
//in ra name của đối tượng
echo $ten->getName();
//kết quả: Lương Hải Minh
//khởi tạo đối tượng Con người
$nguoixem = new ConNguoi();
//hiển thị ra tên người xem
echo $nguoixem->getName();
//Kết quả: Lương Hải Minh


/*
 * Kế thừa từ cha
 */

class NguoiLon extends ConNguoi {
    public function getName()
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }
    public function setName($name)
    {
        parent::setName($name); // TODO: Change the autogenerated stub
    }
}